// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdll3GyczPNsq66Ev4BGaI66Ps4XWEePM',
    appId: '1:1094868225639:web:88c33929b31d390b0dcec2',
    messagingSenderId: '1094868225639',
    projectId: 'mah-fashion',
    authDomain: 'mah-fashion.firebaseapp.com',
    storageBucket: 'mah-fashion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapn94by_2d0vg3ZC_QSRMB256mnfCXO8',
    appId: '1:1094868225639:android:e8eb4771aa48a70d0dcec2',
    messagingSenderId: '1094868225639',
    projectId: 'mah-fashion',
    storageBucket: 'mah-fashion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqH48Y0gJ-bh7md-3MLzl3b9JjvX3mlxk',
    appId: '1:1094868225639:ios:a105003aec7c5a0f0dcec2',
    messagingSenderId: '1094868225639',
    projectId: 'mah-fashion',
    storageBucket: 'mah-fashion.firebasestorage.app',
    iosClientId: '1094868225639-gnl97fu0o0nn1nekv9uvrocaeq2pc79q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahFashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqH48Y0gJ-bh7md-3MLzl3b9JjvX3mlxk',
    appId: '1:1094868225639:ios:a105003aec7c5a0f0dcec2',
    messagingSenderId: '1094868225639',
    projectId: 'mah-fashion',
    storageBucket: 'mah-fashion.firebasestorage.app',
    iosClientId: '1094868225639-gnl97fu0o0nn1nekv9uvrocaeq2pc79q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahFashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdll3GyczPNsq66Ev4BGaI66Ps4XWEePM',
    appId: '1:1094868225639:web:fddce00fe16a74bb0dcec2',
    messagingSenderId: '1094868225639',
    projectId: 'mah-fashion',
    authDomain: 'mah-fashion.firebaseapp.com',
    storageBucket: 'mah-fashion.firebasestorage.app',
  );
}
